version: '3.8'

services:
  blivechat:
    image: xfgryujk/blivechat:latest
    container_name: blivechat
    ports:
      - "12450:12450"
    volumes:
      - blivechat-data:/mnt/data
      - ./plugin.json:/mnt/data/data/plugins/blivechat-tts/plugin.json
      - ./config.ini:/mnt/data/data/config.ini
      - signal-volume:/tmp/signal
    environment:
      - SIGNAL_FILE_PATH=/tmp/signal/config.txt
      - BLC_HOST=blivechat
    restart: unless-stopped

  blivechat-tts:
    build: .
    container_name: blivechat-tts
    depends_on:
      - blivechat
    volumes:
      - signal-volume:/tmp/signal
    environment:
      - SIGNAL_FILE_PATH=/tmp/signal/config.txt
    restart: unless-stopped

volumes:
  blivechat-data:
  signal-volume:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=1m"
